name: Container Security Scan

on:
  schedule:
    - cron: '0 4 * * 2'  # Weekly on Tuesday at 4 AM
  push:
    branches: [ main ]
    paths:
      - '**/Dockerfile'
      - 'docker-compose.yml'

jobs:
  container-scan:
    name: Container Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build Docker images
      run: |
        if [ -f "Dockerfile" ]; then
          docker build -t test-image .
        fi
        if [ -f "docker-compose.yml" ]; then
          docker-compose build
        fi
        
    - name: Run Trivy container scan
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: 'test-image'
        format: 'table'
        exit-code: '0'
      if: hashFiles('Dockerfile') != '' && success()
      
    - name: Run Hadolint Dockerfile linter
      uses: hadolint/hadolint-action@v3.2.0
      with:
        dockerfile: Dockerfile
        failure-threshold: warning
      if: hashFiles('Dockerfile') != ''